version: '2'
services:
    rasveta-app:
        image: rasveta
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rasveta-mysql:3306/rasveta?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rasveta-mysql:
        extends:
            file: mysql.yml
            service: rasveta-mysql
